<SelectScreen>:

	BoxLayout:
		orientation: 'horizontal'
		height: '40dp'
		pos_hint: {'x':0.9, 'y':0.9}
		
		Button:
			id: btn1	
			text: 'Screen 1'
			size_hint_x: .25
			size_hint_y: None
			on_press: root.on_press()
		Button:
			text: 'Screen 2'
			size_hint_x: .25
			size_hint_y: None
		Button:
			text: 'Screen 3'
			size_hint_x: .25
			size_hint_y: None
		Button:
			text: 'Screen 4'
			size_hint_x: .25
			size_hint_y: None